### ISSUE TITLE
  initialize_psk_security() has wrong declaration if AVS_COMMONS_WITH_AVS_CRYPTO_PSK is undefined.

### ISSUE THREAD

**Issue by xaelsouth** [AVSystem/avs_commons#310]
[ix_definition_initialize_psk_security.txt](https://github.com/AVSystem/avs_commons/files/12908076/ix_definition_initialize_psk_security.txt)

initialize_psk_security() has wrong declaration if AVS_COMMONS_WITH_AVS_CRYPTO_PSK is undefined.

patch as txt attached.

**Comment by Kucmasz** [comment]
Hi!
Thank you for you interest and concern. Actually the change you proposed was introduced in [release 5.4.1](https://github.com/AVSystem/avs_commons/releases/tag/5.4.1) last week, so this declaration is fixed in the [latest code version](https://github.com/AVSystem/avs_commons/blob/master/src/net/mbedtls/avs_mbedtls_socket.c#L811). You can also see that we have changed the way of such compile-time functions definitions in favor of having a single function signature and only the function bodies between `#if` directives to avoid such inconsistencies in the future.
Regards,
Tomasz

**Comment by xaelsouth** [comment]
Thanks for clarification in this.

Regards,
Xael
